version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
